name = "pixel-counter"
main = "src/index.js"
compatibility_date = "2025-01-01"

# Fill in the id printed by:  wrangler kv namespace create COUNTER
[[kv_namespaces]]
binding = "COUNTER"
id = "8207ddf222394921b959b792f56300ac"
